In [43]:
# Import pandas library

import pandas as pd

In [44]:
# Load dataset

df = pd.read_csv("/content/Forecasting Case-Sheet1.csv")
df

              State        Date           Total   Category
0           Alabama   1/12/2019    109,574,036   Beverages
1           Arizona   1/12/2019    109,101,595   Beverages
2          Arkansas   1/12/2019     58,049,432   Beverages
3        California   1/12/2019    444,766,891   Beverages
4          Colorado   1/12/2019     89,816,716   Beverages
...             ...         ...             ...        ...
8079       Virginia  31-10-2021    255,221,502   Beverages
8080     Washington  31-10-2021    165,155,956   Beverages
8081  West Virginia  31-10-2021     63,324,231   Beverages
8082      Wisconsin  31-10-2021    138,373,769   Beverages
8083        Wyoming  31-10-2021     19,126,432   Beverages

[8084 rows x 4 columns]

In [45]:
# Check dataset information

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8084 entries, 0 to 8083
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   State     8084 non-null   object
 1   Date      8084 non-null   object
 2   Total     8084 non-null   object
 3   Category  8084 non-null   object
dtypes: object(4)
memory usage: 252.8+ KB

In [46]:
# Check missing values

df.isnull().sum()

State       0
Date        0
Total       0
Category    0
dtype: int64

In [47]:
# Check duplicate rows

df.duplicated().sum()

np.int64(0)

In [48]:
# Convert Date column to datetime format

df['Date'] = pd.to_datetime(
    df['Date'],
    format='mixed',
    dayfirst=True
)

In [49]:
# Display dataset after date conversion

df

              State       Date           Total   Category
0           Alabama 2019-12-01    109,574,036   Beverages
1           Arizona 2019-12-01    109,101,595   Beverages
2          Arkansas 2019-12-01     58,049,432   Beverages
3        California 2019-12-01    444,766,891   Beverages
4          Colorado 2019-12-01     89,816,716   Beverages
...             ...        ...             ...        ...
8079       Virginia 2021-10-31    255,221,502   Beverages
8080     Washington 2021-10-31    165,155,956   Beverages
8081  West Virginia 2021-10-31     63,324,231   Beverages
8082      Wisconsin 2021-10-31    138,373,769   Beverages
8083        Wyoming 2021-10-31     19,126,432   Beverages

[8084 rows x 4 columns]

In [50]:
# Remove commas from Total column

df['Total'] = df['Total'].replace(',', '', regex=True)

# Convert Total column to numeric

df['Total'] = pd.to_numeric(df['Total'])

In [51]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8084 entries, 0 to 8083
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   State     8084 non-null   object
 1   Date      8084 non-null   datetime64[ns]
 2   Total     8084 non-null   int64
 3   Category  8084 non-null   object
dtypes: datetime64[ns](1), int64(1), object(2)
memory usage: 252.8+ KB

In [52]:
df['Category'].unique()

array(['Beverages'], dtype=object)

In [53]:
# Drop Category column

df = df.drop('Category', axis = 1)

In [54]:
df

              State       Date      Total
0           Alabama 2019-12-01  109574036
1           Arizona 2019-12-01  109101595
2          Arkansas 2019-12-01   58049432
3        California 2019-12-01  444766891
4          Colorado 2019-12-01   89816716
...             ...        ...        ...
8079       Virginia 2021-10-31  255221502
8080     Washington 2021-10-31  165155956
8081  West Virginia 2021-10-31   63324231
8082      Wisconsin 2021-10-31  138373769
8083        Wyoming 2021-10-31   19126432

[8084 rows x 3 columns]

In [55]:
# Sort dataset by State and Date

df = df.sort_values(by=['State', 'Date'])

# Reset Index After Sorting

df = df.reset_index(drop=True)

In [56]:
df

        State       Date      Total
0     Alabama 2019-10-06  129106730
1     Alabama 2019-10-13  123782286
2     Alabama 2019-10-20  116218909
3     Alabama 2019-10-27  109968011
4     Alabama 2019-11-03  112189104
...       ...        ...        ...
8079  Wyoming 2023-04-09   21188736
8080  Wyoming 2023-04-16   20958790
8081  Wyoming 2023-04-23   21367217
8082  Wyoming 2023-04-30   22511772
8083  Wyoming 2023-05-07   23276821

[8084 rows x 3 columns]

In [57]:
# final dataset information

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8084 entries, 0 to 8083
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   State   8084 non-null   object
 1   Date    8084 non-null   datetime64[ns]
 2   Total   8084 non-null   int64
dtypes: datetime64[ns](1), int64(1), object(1)
memory usage: 189.6+ KB

In [58]:
# Checking Week Frequency for each State

# Get All States

states = df['State'].unique()

# Loop Through Each State

for state in states:

    # Filter One State

    state_df = df[df['State'] == state]

    # Set Date as Index

    state_df = state_df.set_index('Date')

    # Convert to Weekly Frequency

    state_df = state_df.asfreq('W')

    print(state)
    print(state_df.isnull().sum())

Alabama
State    0
Total    0
dtype: int64
Arizona
State    0
Total    0
dtype: int64
Arkansas
State    0
Total    0
dtype: int64
California
State    0
Total    0
dtype: int64
Colorado
State    0
Total    0
dtype: int64
Connecticut
State    0
Total    0
dtype: int64
Florida
State    0
Total    0
dtype: int64
Georgia
State    0
Total    0
dtype: int64
Illinois
State    0
Total    0
dtype: int64
Indiana
State    0
Total    0
dtype: int64
Iowa
State    0
Total    0
dtype: int64
Kansas
State    0
Total    0
dtype: int64
Kentucky
State    0
Total    0
dtype: int64
Louisiana
State    0
Total    0
dtype: int64
Maine
State    0
Total    0
dtype: int64
Maryland
State    0
Total    0
dtype: int64
Massachusetts
State    0
Total    0
dtype: int64
Michigan
State    0
Total    0
dtype: int64
Minnesota
State    0
Total    0
dtype: int64
Mississippi
State    0
Total    0
dtype: int64
Missouri
State    0
Total    0
dtype: int64
Nebraska
State    0
Total    0
dtype: int64
Nevada
State    0
Total    0
dtype: int64
New Hampshire
State    0
Total    0
dtype: int64
New Mexico
State    0
Total    0
dtype: int64
New York
State    0
Total    0
dtype: int64
North Carolina
State    0
Total    0
dtype: int64
Ohio
State    0
Total    0
dtype: int64
Oklahoma
State    0
Total    0
dtype: int64
Oregon
State    0
Total    0
dtype: int64
Pennsylvania
State    0
Total    0
dtype: int64
Rhode Island
State    0
Total    0
dtype: int64
South Carolina
State    0
Total    0
dtype: int64
South Dakota
State    0
Total    0
dtype: int64
Tennessee
State    0
Total    0
dtype: int64
Texas
State    0
Total    0
dtype: int64
Utah
State    0
Total    0
dtype: int64
Vermont
State    0
Total    0
dtype: int64
Virginia
State    0
Total    0
dtype: int64
Washington
State    0
Total    0
dtype: int64
West Virginia
State    0
Total    0
dtype: int64
Wisconsin
State    0
Total    0
dtype: int64
Wyoming
State    0
Total    0
dtype: int64

In [59]:
# Feature Engineering

# lag_1 feature

df['lag_1'] = df.groupby('State')['Total'].shift(1)

# lag_7 feature

df['lag_7'] = df.groupby('State')['Total'].shift(7)


# lag_30 feature

df['lag_30'] = df.groupby('State')['Total'].shift(30)

In [60]:
df.head(35)

      State       Date      Total        lag_1        lag_7       lag_30
0   Alabama 2019-10-06  129106730          NaN          NaN          NaN
1   Alabama 2019-10-13  123782286  129106730.0          NaN          NaN
2   Alabama 2019-10-20  116218909  123782286.0          NaN          NaN
3   Alabama 2019-10-27  109968011  116218909.0          NaN          NaN
4   Alabama 2019-11-03  112189104  109968011.0          NaN          NaN
5   Alabama 2019-11-10  110932913  112189104.0          NaN          NaN
6   Alabama 2019-11-17  109056410  110932913.0          NaN          NaN
7   Alabama 2019-11-24  113040422  109056410.0  129106730.0          NaN
8   Alabama 2019-12-01  109574036  113040422.0  123782286.0          NaN
9   Alabama 2019-12-08  108083724  109574036.0  116218909.0          NaN
10  Alabama 2019-12-15  108528456  108083724.0  109968011.0          NaN
11  Alabama 2019-12-22  116541575  108528456.0  112189104.0          NaN
12  Alabama 2019-12-29  106949922  116541575.0  110932913.0          NaN
13  Alabama 2020-01-05  104239954  106949922.0  109056410.0          NaN
14  Alabama 2020-01-12  108717628  104239954.0  113040422.0          NaN
15  Alabama 2020-01-19  105904866  108717628.0  109574036.0          NaN
16  Alabama 2020-01-26  106265737  105904866.0  108083724.0          NaN
17  Alabama 2020-02-02  108358280  106265737.0  108528456.0          NaN
18  Alabama 2020-02-09  109022482  108358280.0  116541575.0          NaN
19  Alabama 2020-02-16  107397612  109022482.0  106949922.0          NaN
20  Alabama 2020-02-23  107801054  107397612.0  104239954.0          NaN
21  Alabama 2020-03-01  116651493  107801054.0  108717628.0          NaN
22  Alabama 2020-03-08  119441834  116651493.0  105904866.0          NaN
23  Alabama 2020-03-15  132632134  119441834.0  106265737.0          NaN
24  Alabama 2020-03-22  127145065  132632134.0  108358280.0          NaN
25  Alabama 2020-03-29  116657084  127145065.0  109022482.0          NaN
26  Alabama 2020-04-05  123259529  116657084.0  107397612.0          NaN
27  Alabama 2020-04-12  117506179  123259529.0  107801054.0          NaN
28  Alabama 2020-04-19  117742073  117506179.0  116651493.0          NaN
29  Alabama 2020-04-26  118114595  117742073.0  119441834.0          NaN
30  Alabama 2020-05-03  128066131  118114595.0  132632134.0  129106730.0
31  Alabama 2020-05-10  127906087  128066131.0  127145065.0  123782286.0
32  Alabama 2020-05-17  130340051  127906087.0  116657084.0  116218909.0
33  Alabama 2020-05-24  134708619  130340051.0  123259529.0  109968011.0
34  Alabama 2020-05-31  129887877  134708619.0  117506179.0  112189104.0

In [61]:
# Rolling mean feature

df['rolling_mean_7'] = (

    df.groupby('State')['Total']

    .transform(lambda x: x.shift(1).rolling(7).mean())

)

In [62]:
# Rolling std feature

df['rolling_std_7'] = (

    df.groupby('State')['Total']

    .transform(lambda x: x.shift(1).rolling(7).std())

)

In [63]:
# Day of week feature

df['day_of_week'] = df['Date'].dt.dayofweek

# Month feature

df['month'] = df['Date'].dt.month

# Week feature

df['week'] = df['Date'].dt.isocalendar().week

# Year feature

df['year'] = df['Date'].dt.year

In [64]:
df = df.dropna()

In [65]:
df.head()

,State,Date,Total,lag_1,lag_7,lag_30,rolling_mean_7,rolling_std_7,day_of_week,month,week,year
30,Alabama,2020-05-03,128066131,118114595.0,132632134.0,129106730.0,1.218652e+08,6.095637e+06,6,5,18,2020
31,Alabama,2020-05-10,127906087,128066131.0,127145065.0,123782286.0,1.212130e+08,4.873182e+06,6,5,19,2020
32,Alabama,2020-05-17,130340051,127906087.0,116657084.0,116218909.0,1.213217e+08,5.033435e+06,6,5,20,2020
33,Alabama,2020-05-24,134708619,130340051.0,123259529.0,109968011.0,1.232764e+08,5.550367e+06,6,5,21,2020
34,Alabama,2020-05-31,129887877,134708619.0,117506179.0,112189104.0,1.249120e+08,7.033365e+06,6,5,22,2020

In [66]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6794 entries, 30 to 8083
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   State           6794 non-null   object
 1   Date            6794 non-null   datetime64[ns]
 2   Total           6794 non-null   int64
 3   lag_1           6794 non-null   float64
 4   lag_7           6794 non-null   float64
 5   lag_30          6794 non-null   float64
 6   rolling_mean_7  6794 non-null   float64
 7   rolling_std_7   6794 non-null   float64
 8   day_of_week     6794 non-null   int32
 9   month           6794 non-null   int32
 10  week            6794 non-null   UInt32
 11  year            6794 non-null   int32
dtypes: UInt32(1), datetime64[ns](1), float64(5), int32(3), int64(1), object(1)
memory usage: 590.5+ KB

In [67]:
df.isnull().sum()

State             0
Date              0
Total             0
lag_1             0
lag_7             0
lag_30            0
rolling_mean_7    0
rolling_std_7     0
day_of_week       0
month             0
week              0
year              0
dtype: int64

In [68]:
pip install holidays

Requirement already satisfied: holidays in /usr/local/lib/python3.12/dist-packages (0.95)
Requirement already satisfied: python-dateutil<3,>=2.9.0.post0 in /usr/local/lib/python3.12/dist-packages (from holidays) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil<3,>=2.9.0.post0->holidays) (1.17.0)

In [69]:
import holidays

# Ignore warnings
import warnings
warnings.filterwarnings('ignore')

In [70]:
# Holiday flag feature

us_holidays = holidays.US()

df['holiday_flag'] = df['Date'].apply(
    lambda x: 1 if x in us_holidays else 0
)

In [71]:
df.head()

,State,Date,Total,lag_1,lag_7,lag_30,rolling_mean_7,rolling_std_7,day_of_week,month,week,year,holiday_flag
30,Alabama,2020-05-03,128066131,118114595.0,132632134.0,129106730.0,1.218652e+08,6.095637e+06,6,5,18,2020,0
31,Alabama,2020-05-10,127906087,128066131.0,127145065.0,123782286.0,1.212130e+08,4.873182e+06,6,5,19,2020,0
32,Alabama,2020-05-17,130340051,127906087.0,116657084.0,116218909.0,1.213217e+08,5.033435e+06,6,5,20,2020,0
33,Alabama,2020-05-24,134708619,130340051.0,123259529.0,109968011.0,1.232764e+08,5.550367e+06,6,5,21,2020,0
34,Alabama,2020-05-31,129887877,134708619.0,117506179.0,112189104.0,1.249120e+08,7.033365e+06,6,5,22,2020,0

In [72]:
df = df.rename(columns={'Total': 'Sales'})

In [73]:
df

,State,Date,Sales,lag_1,lag_7,lag_30,rolling_mean_7,rolling_std_7,day_of_week,month,week,year,holiday_flag
30,Alabama,2020-05-03,128066131,118114595.0,132632134.0,129106730.0,1.218652e+08,6.095637e+06,6,5,18,2020,0
31,Alabama,2020-05-10,127906087,128066131.0,127145065.0,123782286.0,1.212130e+08,4.873182e+06,6,5,19,2020,0
32,Alabama,2020-05-17,130340051,127906087.0,116657084.0,116218909.0,1.213217e+08,5.033435e+06,6,5,20,2020,0
33,Alabama,2020-05-24,134708619,130340051.0,123259529.0,109968011.0,1.232764e+08,5.550367e+06,6,5,21,2020,0
34,Alabama,2020-05-31,129887877,134708619.0,117506179.0,112189104.0,1.249120e+08,7.033365e+06,6,5,22,2020,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8079,Wyoming,2023-04-09,21188736,20543373.0,20096421.0,22719550.0,2.088362e+07,8.685540e+05,6,4,14,2023,0
8080,Wyoming,2023-04-16,20958790,21188736.0,19972751.0,22254099.0,2.103966e+07,7.988833e+05,6,4,15,2023,0
8081,Wyoming,2023-04-23,21367217,20958790.0,21887585.0,21497707.0,2.118052e+07,6.530229e+05,6,4,16,2023,0
8082,Wyoming,2023-04-30,22511772,21367217.0,21955065.0,21704018.0,2.110619e+07,5.852164e+05,6,4,17,2023,0
8083,Wyoming,2023-05-07,23276821,22511772.0,21499314.0,21604743.0,2.118572e+07,7.377523e+05,6,5,18,2023,0

In [74]:
# Forecasting Models

In [75]:
df.head()

,State,Date,Sales,lag_1,lag_7,lag_30,rolling_mean_7,rolling_std_7,day_of_week,month,week,year,holiday_flag
30,Alabama,2020-05-03,128066131,118114595.0,132632134.0,129106730.0,1.218652e+08,6.095637e+06,6,5,18,2020,0
31,Alabama,2020-05-10,127906087,128066131.0,127145065.0,123782286.0,1.212130e+08,4.873182e+06,6,5,19,2020,0
32,Alabama,2020-05-17,130340051,127906087.0,116657084.0,116218909.0,1.213217e+08,5.033435e+06,6,5,20,2020,0
33,Alabama,2020-05-24,134708619,130340051.0,123259529.0,109968011.0,1.232764e+08,5.550367e+06,6,5,21,2020,0
34,Alabama,2020-05-31,129887877,134708619.0,117506179.0,112189104.0,1.249120e+08,7.033365e+06,6,5,22,2020,0

In [76]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6794 entries, 30 to 8083
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   State           6794 non-null   object
 1   Date            6794 non-null   datetime64[ns]
 2   Sales           6794 non-null   int64
 3   lag_1           6794 non-null   float64
 4   lag_7           6794 non-null   float64
 5   lag_30          6794 non-null   float64
 6   rolling_mean_7  6794 non-null   float64
 7   rolling_std_7   6794 non-null   float64
 8   day_of_week     6794 non-null   int32
 9   month           6794 non-null   int32
 10  week            6794 non-null   UInt32
 11  year            6794 non-null   int32
 12  holiday_flag    6794 non-null   int64
dtypes: UInt32(1), datetime64[ns](1), float64(5), int32(3), int64(2), object(1)
memory usage: 643.6+ KB

In [77]:
df.isnull().sum()

State             0
Date              0
Sales             0
lag_1             0
lag_7             0
lag_30            0
rolling_mean_7    0
rolling_std_7     0
day_of_week       0
month             0
week              0
year              0
holiday_flag      0
dtype: int64

In [78]:
# SARIMA Model

# Import libraries

import warnings
warnings.filterwarnings("ignore")

import pandas as pd
import numpy as np

from statsmodels.tsa.statespace.sarimax import SARIMAX

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error
)

In [79]:
# Store SARIMA results

s_results = []

In [80]:
# Get all states

states = df['State'].unique()

In [81]:
# Run SARIMA model for every state

for state in states:

    # Filter one state
    state_df = df[df['State'] == state]

    # Set Date as index
    state_df = state_df.set_index('Date')

    # Convert to weekly frequency
    state_df = state_df.asfreq('W')

    # Sales time series
    sales_series = state_df['Sales']

    # Train data
    train = sales_series[:-8]

    # Validation data
    valid = sales_series[-8:]

    # Build SARIMA model
    model = SARIMAX(
        train,
        order=(1,1,1),
        seasonal_order=(1,1,1,52)
    )

    # Fit model
    model_fit = model.fit(disp=False)

    # Forecast next 8 weeks
    forecast = model_fit.forecast(steps=8)

    # Evaluation metrics
    mae = mean_absolute_error(valid, forecast)

    rmse = np.sqrt(
        mean_squared_error(valid, forecast)
    )

    # Store results
    s_results.append([
        state,
        mae,
        rmse
    ])

In [82]:
# Convert SARIMA results into table

s_results_df = pd.DataFrame(
    s_results,
    columns=['State', 'MAE', 'RMSE']
)

s_results_df

             State           MAE          RMSE
0          Alabama  1.952460e+07  2.125177e+07
1          Arizona  2.081571e+07  2.167951e+07
2         Arkansas  6.737179e+06  7.529124e+06
3       California  9.507243e+07  9.989785e+07
4         Colorado  1.430734e+07  1.613281e+07
5      Connecticut  7.533407e+06  8.749334e+06
6          Florida  7.599399e+07  8.623034e+07
7          Georgia  3.284787e+07  3.649056e+07
8         Illinois  3.693123e+07  4.008662e+07
9          Indiana  1.826415e+07  2.027969e+07
10            Iowa  7.266857e+06  8.236678e+06
11          Kansas  6.007330e+06  6.986492e+06
12        Kentucky  1.587874e+07  1.717732e+07
13       Louisiana  2.253859e+07  2.363076e+07
14           Maine  3.051323e+06  3.597958e+06
15        Maryland  1.616255e+07  1.871994e+07
16   Massachusetts  1.621480e+07  1.862119e+07
17        Michigan  2.166966e+07  2.467218e+07
18       Minnesota  9.123981e+06  1.094697e+07
19     Mississippi  1.005480e+07  1.156903e+07
20        Missouri  1.129064e+07  1.319386e+07
21        Nebraska  3.438651e+06  4.158626e+06
22          Nevada  1.117880e+07  1.157775e+07
23   New Hampshire  4.053203e+06  4.710589e+06
24      New Mexico  8.032444e+06  8.418057e+06
25        New York  3.372612e+07  4.026173e+07
26  North Carolina  3.612228e+07  3.951476e+07
27            Ohio  3.324521e+07  3.578650e+07
28        Oklahoma  8.212212e+06  9.477079e+06
29          Oregon  6.907381e+06  7.861880e+06
30    Pennsylvania  3.316143e+07  3.807887e+07
31    Rhode Island  1.423561e+06  1.850030e+06
32  South Carolina  1.763962e+07  1.924753e+07
33    South Dakota  1.582156e+06  1.768598e+06
34       Tennessee  2.123723e+07  2.316855e+07
35           Texas  9.836831e+07  1.025469e+08
36            Utah  7.342122e+06  7.691362e+06
37         Vermont  9.685772e+05  1.182030e+06
38        Virginia  2.639622e+07  2.997478e+07
39      Washington  1.487612e+07  1.643738e+07
40   West Virginia  5.841781e+06  6.591881e+06
41       Wisconsin  1.184433e+07  1.351630e+07
42         Wyoming  1.586977e+06  1.707015e+06

In [83]:
# Average MAE and RMSE

print("Average MAE:", s_results_df['MAE'].mean())

print("Average RMSE:", s_results_df['RMSE'].mean())

Average MAE: 19871439.374282766
Average RMSE: 21888563.416335866

In [84]:
# Facebook Prophet Model

!pip install prophet

Requirement already satisfied: prophet in /usr/local/lib/python3.12/dist-packages (1.3.0)
Requirement already satisfied: cmdstanpy>=1.0.4 in /usr/local/lib/python3.12/dist-packages (from prophet) (1.3.0)
Requirement already satisfied: numpy>=1.15.4 in /usr/local/lib/python3.12/dist-packages (from prophet) (2.0.2)
Requirement already satisfied: matplotlib>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from prophet) (3.10.0)
Requirement already satisfied: pandas>=1.0.4 in /usr/local/lib/python3.12/dist-packages (from prophet) (2.2.2)
Requirement already satisfied: holidays<1,>=0.25 in /usr/local/lib/python3.12/dist-packages (from prophet) (0.95)
Requirement already satisfied: tqdm>=4.36.1 in /usr/local/lib/python3.12/dist-packages (from prophet) (4.67.3)
Requirement already satisfied: importlib_resources in /usr/local/lib/python3.12/dist-packages (from prophet) (7.1.0)
Requirement already satisfied: stanio<2.0.0,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from cmdstanpy>=1.0.4->prophet) (0.5.1)
Requirement already satisfied: python-dateutil<3,>=2.9.0.post0 in /usr/local/lib/python3.12/dist-packages (from holidays<1,>=0.25->prophet) (2.9.0.post0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=2.0.0->prophet) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=2.0.0->prophet) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=2.0.0->prophet) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=2.0.0->prophet) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=2.0.0->prophet) (26.1)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=2.0.0->prophet) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=2.0.0->prophet) (3.3.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.4->prophet) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.4->prophet) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil<3,>=2.9.0.post0->holidays<1,>=0.25->prophet) (1.17.0)

In [85]:
# Import libraries

import numpy as np
import pandas as pd

from prophet import Prophet

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error
)

In [86]:
# Store Prophet results

p_results = []

In [87]:
import logging

logging.getLogger('cmdstanpy').disabled = True

import warnings
warnings.filterwarnings("ignore")

In [88]:
# Run Prophet model for every state

for state in states:

    # Filter one state
    state_df = df[df['State'] == state].copy()

    # Select required columns
    state_df = state_df[['Date', 'Sales']]

    # Rename columns for Prophet
    state_df = state_df.rename(
        columns={
            'Date': 'ds',
            'Sales': 'y'
        }
    )

    # Train data
    train = state_df[:-8]

    # Validation data
    valid = state_df[-8:]

    # Create Prophet model
    model = Prophet()

    # Train model
    model.fit(train)

    # Create future dataframe
    future = model.make_future_dataframe(
        periods=8,
        freq='W'
    )

    # Forecast
    forecast = model.predict(future)

    # Last 8 predictions
    predictions = forecast['yhat'][-8:].values

    # Evaluation metrics
    mae = mean_absolute_error(
        valid['y'],
        predictions
    )

    rmse = np.sqrt(
        mean_squared_error(
            valid['y'],
            predictions
        )
    )

    # Store results
    p_results.append([
        state,
        mae,
        rmse
    ])

INFO:prophet:Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.
INFO:prophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:prophet:Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.
INFO:prophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:prophet:Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.
INFO:prophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:prophet:Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.
INFO:prophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:prophet:Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.
INFO:prophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:prophet:Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.
INFO:prophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:prophet:Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.
INFO:prophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:prophet:Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.
INFO:prophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:prophet:Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.
INFO:prophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:prophet:Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.
INFO:prophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:prophet:Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.
INFO:prophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:prophet:Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.
INFO:prophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:prophet:Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.
INFO:prophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:prophet:Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.
INFO:prophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:prophet:Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.
INFO:prophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:prophet:Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.
INFO:prophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:prophet:Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.
INFO:prophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:prophet:Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.
INFO:prophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:prophet:Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.
INFO:prophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:prophet:Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.
INFO:prophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:prophet:Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.
INFO:prophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:prophet:Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.
INFO:prophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:prophet:Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.
INFO:prophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:prophet:Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.
INFO:prophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:prophet:Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.
INFO:prophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:prophet:Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.
INFO:prophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:prophet:Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.
INFO:prophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:prophet:Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.
INFO:prophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:prophet:Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.
INFO:prophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:prophet:Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.
INFO:prophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:prophet:Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.
INFO:prophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:prophet:Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.
INFO:prophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:prophet:Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.
INFO:prophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:prophet:Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.
INFO:prophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:prophet:Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.
INFO:prophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:prophet:Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.
INFO:prophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:prophet:Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.
INFO:prophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:prophet:Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.
INFO:prophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:prophet:Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.
INFO:prophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:prophet:Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.
INFO:prophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:prophet:Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.
INFO:prophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:prophet:Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.
INFO:prophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:prophet:Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.
INFO:prophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.

In [89]:
 # Convert Prophet results into table

p_results_df = pd.DataFrame(
    p_results,
    columns=['State', 'MAE', 'RMSE']
)

p_results_df

             State           MAE          RMSE
0          Alabama  7.948862e+06  9.380401e+06
1          Arizona  1.022416e+07  1.209338e+07
2         Arkansas  5.851136e+06  6.247844e+06
3       California  2.981290e+07  3.594174e+07
4         Colorado  7.922269e+06  9.251437e+06
5      Connecticut  3.787147e+06  4.213006e+06
6          Florida  1.379141e+07  1.497131e+07
7          Georgia  1.248534e+07  1.554465e+07
8         Illinois  1.219686e+07  1.422876e+07
9          Indiana  1.057491e+07  1.153270e+07
10            Iowa  4.993267e+06  5.464215e+06
11          Kansas  4.620859e+06  4.973989e+06
12        Kentucky  7.296423e+06  8.111838e+06
13       Louisiana  5.222677e+06  6.854266e+06
14           Maine  2.593263e+06  2.959095e+06
15        Maryland  5.304734e+06  6.141581e+06
16   Massachusetts  8.804879e+06  9.876015e+06
17        Michigan  1.299016e+07  1.415862e+07
18       Minnesota  7.876448e+06  9.327595e+06
19     Mississippi  3.954067e+06  5.115423e+06
20        Missouri  1.061071e+07  1.122903e+07
21        Nebraska  2.137154e+06  2.582704e+06
22          Nevada  4.269354e+06  4.983099e+06
23   New Hampshire  3.055080e+06  3.551244e+06
24      New Mexico  3.295383e+06  3.645414e+06
25        New York  2.001373e+07  2.237548e+07
26  North Carolina  1.085012e+07  1.245085e+07
27            Ohio  1.233009e+07  1.399515e+07
28        Oklahoma  5.182095e+06  6.465298e+06
29          Oregon  5.173187e+06  6.209932e+06
30    Pennsylvania  1.393416e+07  1.474563e+07
31    Rhode Island  1.474195e+06  1.647732e+06
32  South Carolina  7.506970e+06  8.311841e+06
33    South Dakota  1.798567e+06  2.039672e+06
34       Tennessee  8.396416e+06  9.366929e+06
35           Texas  4.030024e+07  4.640960e+07
36            Utah  3.574849e+06  4.243982e+06
37         Vermont  1.009390e+06  1.161478e+06
38        Virginia  1.011409e+07  1.076797e+07
39      Washington  7.920410e+06  9.363568e+06
40   West Virginia  2.651703e+06  3.255902e+06
41       Wisconsin  8.394863e+06  9.511384e+06
42         Wyoming  1.203178e+06  1.438076e+06

In [90]:
# Average MAE and RMSE

print("Average MAE:", p_results_df['MAE'].mean())

print("Average RMSE:", p_results_df['RMSE'].mean())

Average MAE: 8452272.497489663
Average RMSE: 9677670.50909242

In [91]:
# XGBoost Model

!pip install xgboost

Requirement already satisfied: xgboost in /usr/local/lib/python3.12/dist-packages (3.2.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from xgboost) (2.0.2)
Requirement already satisfied: nvidia-nccl-cu12 in /usr/local/lib/python3.12/dist-packages (from xgboost) (2.30.4)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from xgboost) (1.16.3)

In [92]:
# Import libraries

import numpy as np
import pandas as pd

from xgboost import XGBRegressor

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error
)

In [93]:
# Store XGBoost results

xgb_results = []

In [94]:
# Run XGBoost for every state

for state in df['State'].unique():

    # Filter one state
    state_df = df[df['State'] == state]

    # Features
    X = state_df.drop(
        columns=['State', 'Date', 'Sales']
    )

    # Target
    y = state_df['Sales']

    # Train data
    X_train = X[:-8]
    y_train = y[:-8]

    # Validation data
    X_valid = X[-8:]
    y_valid = y[-8:]

    # Build model
    model = XGBRegressor()

    # Train model
    model.fit(X_train, y_train)

    # Forecast
    forecast = model.predict(X_valid)

    # Evaluation metrics
    mae = mean_absolute_error(
        y_valid,
        forecast
    )

    rmse = np.sqrt(
        mean_squared_error(
            y_valid,
            forecast
        )
    )

    # Store results
    xgb_results.append([
        state,
        mae,
        rmse
    ])

In [95]:
# Convert XGBoost results into table

xgb_results_df = pd.DataFrame(
    xgb_results,
    columns=['State', 'MAE', 'RMSE']
)

xgb_results_df

             State          MAE          RMSE
0          Alabama   4595814.00  6.639327e+06
1          Arizona   8498526.00  1.260969e+07
2         Arkansas   3804629.00  5.082306e+06
3       California  33212336.00  4.407710e+07
4         Colorado   8455756.00  9.615967e+06
5      Connecticut   2686636.00  3.662506e+06
6          Florida  59311448.00  6.012912e+07
7          Georgia  10355036.00  1.197476e+07
8         Illinois  11829520.00  1.854221e+07
9          Indiana   4707546.00  7.207856e+06
10            Iowa   3201455.00  4.123715e+06
11          Kansas   2654814.00  3.830215e+06
12        Kentucky   4504136.00  6.868107e+06
13       Louisiana   5644204.00  7.987673e+06
14           Maine   2077301.50  2.508800e+06
15        Maryland   5143300.00  6.042340e+06
16   Massachusetts   9246828.00  1.082246e+07
17        Michigan   8057576.00  9.879297e+06
18       Minnesota   6524046.00  8.434200e+06
19     Mississippi   3088039.00  3.794043e+06
20        Missouri   6832318.00  1.005713e+07
21        Nebraska   1737067.00  2.372269e+06
22          Nevada   4295273.00  5.324822e+06
23   New Hampshire   1955262.50  2.506558e+06
24      New Mexico   2937815.00  4.221297e+06
25        New York  16995340.00  2.332654e+07
26  North Carolina   5163056.00  6.891791e+06
27            Ohio  12146640.00  1.466499e+07
28        Oklahoma   4869436.00  6.073032e+06
29          Oregon   3253693.00  4.440532e+06
30    Pennsylvania   7153264.00  1.204551e+07
31    Rhode Island   1040081.00  1.336671e+06
32  South Carolina   6122866.00  7.458456e+06
33    South Dakota    795904.00  9.036428e+05
34       Tennessee   4282066.00  5.857502e+06
35           Texas  26395360.00  3.153841e+07
36            Utah   3439663.00  4.022425e+06
37         Vermont    726390.25  8.760779e+05
38        Virginia   7093356.00  9.134741e+06
39      Washington   5519100.00  6.471826e+06
40   West Virginia   2558434.00  3.421977e+06
41       Wisconsin   6333228.00  8.253314e+06
42         Wyoming    863969.75  9.715103e+05

In [96]:
# Average MAE and RMSE

print("Average MAE:", xgb_results_df['MAE'].mean())

print("Average RMSE:", xgb_results_df['RMSE'].mean())

Average MAE: 7676942.534883721
Average RMSE: 9674481.775578983

In [97]:
# LSTM Model

!pip install tensorflow

Requirement already satisfied: tensorflow in /usr/local/lib/python3.12/dist-packages (2.20.0)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.7.0)
Requirement already satisfied: google_pasta>=0.1.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt_einsum>=2.3.2 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from tensorflow) (26.1)
Requirement already satisfied: protobuf>=5.28.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (5.29.6)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.32.4)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from tensorflow) (75.2.0)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.3.0)
Requirement already satisfied: typing_extensions>=3.6.6 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (4.15.0)
Requirement already satisfied: wrapt>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.1.2)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.80.0)
Requirement already satisfied: tensorboard~=2.20.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.20.0)
Requirement already satisfied: keras>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.13.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.0.2)
Requirement already satisfied: h5py>=3.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.16.0)
Requirement already satisfied: ml_dtypes<1.0.0,>=0.5.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.5.4)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from astunparse>=1.6.0->tensorflow) (0.47.0)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras>=3.10.0->tensorflow) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras>=3.10.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras>=3.10.0->tensorflow) (0.19.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.13)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (2026.4.22)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.20.0->tensorflow) (3.10.2)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.20.0->tensorflow) (11.3.0)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.20.0->tensorflow) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.20.0->tensorflow) (3.1.8)
Requirement already satisfied: markupsafe>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from werkzeug>=1.0.1->tensorboard~=2.20.0->tensorflow) (3.0.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.10.0->tensorflow) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.10.0->tensorflow) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras>=3.10.0->tensorflow) (0.1.2)

In [98]:
# Import libraries

import numpy as np
import pandas as pd

from sklearn.preprocessing import MinMaxScaler

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error
)

from tensorflow.keras.models import Sequential

from tensorflow.keras.layers import (
    LSTM,
    Dense
)

In [99]:
# Store LSTM results

lstm_results = []

In [101]:
# Run LSTM model for every state

for state in states:

    # Filter one state
    state_df = df[df['State'] == state].copy()

    # Sales values
    sales = state_df['Sales'].values.reshape(-1, 1)

    # Split train and validation
    train_sales = sales[:-8]

    valid_sales = sales[-8:]

    # Scale only training data
    scaler = MinMaxScaler()

    train_scaled = scaler.fit_transform(train_sales)

    valid_scaled = scaler.transform(valid_sales)

    # Train sequences

    X_train = []

    y_train = []

    for i in range(30, len(train_scaled)):

        X_train.append(
            train_scaled[i-30:i]
        )

        y_train.append(
            train_scaled[i]
        )

    X_train = np.array(X_train)

    y_train = np.array(y_train)

    # Validation sequences

    X_valid = []

    y_valid = []

    combined = np.concatenate(
        [train_scaled[-30:], valid_scaled]
    )

    for i in range(30, len(combined)):

        X_valid.append(
            combined[i-30:i]
        )

        y_valid.append(
            combined[i]
        )

    X_valid = np.array(X_valid)

    y_valid = np.array(y_valid)

    # Build model

    model = Sequential()

    model.add(
        LSTM(
            50,
            activation='relu',
            input_shape=(X_train.shape[1], 1)
        )
    )

    model.add(Dense(1))

    # Compile model
    model.compile(
        optimizer='adam',
        loss='mse'
    )

    # Train model
    model.fit(
        X_train,
        y_train,
        epochs=20,
        batch_size=16,
        verbose=0
    )

    # Predictions
    predictions = model.predict(X_valid)

    # Inverse transform predictions
    predictions = scaler.inverse_transform(
        predictions
    )

    # Inverse transform actual values
    y_valid_actual = scaler.inverse_transform(
        y_valid
    )

    # Evaluation metrics
    mae = mean_absolute_error(
        y_valid_actual,
        predictions
    )

    rmse = np.sqrt(
        mean_squared_error(
            y_valid_actual,
            predictions
        )
    )

    # Store results
    lstm_results.append([
        state,
        mae,
        rmse
    ])

WARNING:tensorflow:5 out of the last 5 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x7f6f0596afc0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 224ms/step

WARNING:tensorflow:6 out of the last 6 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x7f6f04eeb880> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 176ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 172ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 187ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 175ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 176ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 262ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 185ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 244ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 174ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 186ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 172ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 180ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 286ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 194ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 202ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 518ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 204ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 201ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 184ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 204ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 182ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 179ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 344ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 198ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 278ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 187ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 227ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 278ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 180ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 174ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 201ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 202ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 179ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 352ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 253ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 255ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 201ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 204ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 184ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 184ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 185ms/step

In [102]:
# Convert LSTM results into table

lstm_results_df = pd.DataFrame(
    lstm_results,
    columns=['State', 'MAE', 'RMSE']
)

lstm_results_df

             State           MAE          RMSE
0          Alabama  4.703512e+06  6.507983e+06
1          Arizona  1.116475e+07  1.307783e+07
2         Arkansas  4.959246e+06  5.382076e+06
3       California  2.468639e+07  2.787620e+07
4          Alabama  7.148370e+06  8.766767e+06
5          Arizona  9.979661e+06  1.179576e+07
6         Arkansas  3.312584e+06  3.908831e+06
7       California  2.637836e+07  2.982629e+07
8         Colorado  6.439720e+06  7.317008e+06
9      Connecticut  2.681190e+06  3.433884e+06
10         Florida  1.836562e+07  2.449306e+07
11         Georgia  1.218703e+07  1.352287e+07
12        Illinois  1.217255e+07  1.396896e+07
13         Indiana  9.514410e+06  1.037341e+07
14            Iowa  4.880371e+06  5.222197e+06
15          Kansas  3.561650e+06  3.937678e+06
16        Kentucky  8.020034e+06  8.956064e+06
17       Louisiana  6.030236e+06  7.711779e+06
18           Maine  1.603416e+06  1.877805e+06
19        Maryland  4.841662e+06  7.776536e+06
20   Massachusetts  7.778575e+06  8.578785e+06
21        Michigan  8.872922e+06  1.024710e+07
22       Minnesota  7.189782e+06  8.361506e+06
23     Mississippi  4.845965e+06  6.284387e+06
24        Missouri  8.444078e+06  9.403604e+06
25        Nebraska  2.925128e+06  3.212208e+06
26          Nevada  4.166317e+06  4.880362e+06
27   New Hampshire  2.153430e+06  2.640469e+06
28      New Mexico  3.472149e+06  4.028315e+06
29        New York  1.541375e+07  1.959677e+07
30  North Carolina  7.745164e+06  9.578988e+06
31            Ohio  9.427468e+06  1.070563e+07
32        Oklahoma  4.854913e+06  6.061504e+06
33          Oregon  4.672437e+06  5.690134e+06
34    Pennsylvania  1.979946e+07  2.241050e+07
35    Rhode Island  8.416415e+05  1.072437e+06
36  South Carolina  3.715670e+06  4.958418e+06
37    South Dakota  9.169950e+05  1.076829e+06
38       Tennessee  9.366284e+06  1.012680e+07
39           Texas  2.554308e+07  3.385652e+07
40            Utah  5.704534e+06  6.196165e+06
41         Vermont  6.888860e+05  8.254468e+05
42        Virginia  8.297352e+06  1.022277e+07
43      Washington  6.491725e+06  8.048548e+06
44   West Virginia  3.575886e+06  4.247586e+06
45       Wisconsin  7.147922e+06  7.940060e+06
46         Wyoming  7.186848e+05  9.374949e+05

In [103]:
# Average MAE and RMSE

print("Average MAE:", lstm_results_df['MAE'].mean())

print("Average RMSE:", lstm_results_df['RMSE'].mean())

Average MAE: 7817041.832446809
Average RMSE: 9296219.876031553

In [104]:
# Add model names

s_results_df['Model'] = 'SARIMA'

xgb_results_df['Model'] = 'XGBoost'

p_results_df['Model'] = 'Prophet'

lstm_results_df['Model'] = 'LSTM'

# Combine all results

final_results = pd.concat([
    s_results_df,
    xgb_results_df,
    p_results_df,
    lstm_results_df
])

# Reset index

final_results.reset_index(drop=True, inplace=True)

# Display results

final_results

             State           MAE          RMSE   Model
0          Alabama  1.952460e+07  2.125177e+07  SARIMA
1          Arizona  2.081571e+07  2.167951e+07  SARIMA
2         Arkansas  6.737179e+06  7.529124e+06  SARIMA
3       California  9.507243e+07  9.989785e+07  SARIMA
4         Colorado  1.430734e+07  1.613281e+07  SARIMA
..             ...           ...           ...     ...
171       Virginia  8.297352e+06  1.022277e+07    LSTM
172     Washington  6.491725e+06  8.048548e+06    LSTM
173  West Virginia  3.575886e+06  4.247586e+06    LSTM
174      Wisconsin  7.147922e+06  7.940060e+06    LSTM
175        Wyoming  7.186848e+05  9.374949e+05    LSTM

[176 rows x 4 columns]

In [105]:
final_results.groupby('Model')[['MAE', 'RMSE']].mean()

                  MAE          RMSE
Model
LSTM     7.817042e+06  9.296220e+06
Prophet  8.452272e+06  9.677671e+06
SARIMA   1.987144e+07  2.188856e+07
XGBoost  7.676943e+06  9.674482e+06

In [106]:
best_model = final_results.groupby('Model')['RMSE'].mean().idxmin()

print("Best Model:", best_model)

Best Model: LSTM

In [107]:
# 8 Weeks Forecasting Using Best Model (LSTM)

In [108]:
# Store future forecasts

future_forecasts = []

# Get all states

states = df['State'].unique()

In [109]:
# Run forecasting for every state

for state in states:

    # Filter state data
    state_df = df[df['State'] == state].copy()

    # Sales values
    sales = state_df['Sales'].values.reshape(-1, 1)

    # Scale data
    scaler = MinMaxScaler()

    scaled_sales = scaler.fit_transform(sales)

    # Create sequences
    X = []
    y = []

    for i in range(30, len(scaled_sales)):

        X.append(scaled_sales[i-30:i])

        y.append(scaled_sales[i])

    # Convert to numpy arrays
    X = np.array(X)

    y = np.array(y)

    # Build model
    model = Sequential()

    model.add(
        LSTM(
            50,
            activation='relu',
            input_shape=(30, 1)
        )
    )

    model.add(Dense(1))

    # Compile model
    model.compile(
        optimizer='adam',
        loss='mse'
    )

    # Train model
    model.fit(
        X,
        y,
        epochs=20,
        batch_size=16,
        verbose=0
    )

    # Last 30 values
    last_30 = scaled_sales[-30:]

    # Reshape input
    X_input = last_30.reshape(1, 30, 1)

    # Predict next 8 weeks
    future_predictions = []

    for i in range(8):

        pred = model.predict(
            X_input,
            verbose=0
        )

        future_predictions.append(
            pred[0][0]
        )

        # Update input
        X_input = np.append(
            X_input[:, 1:, :],
            [[[pred[0][0]]]],
            axis=1
        )

    # Inverse transform
    future_predictions = scaler.inverse_transform(
        np.array(future_predictions).reshape(-1, 1)
    )

    # Store results
    for week in range(8):

        future_forecasts.append([
            state,
            f"Week {week+1}",
            future_predictions[week][0]
        ])

In [110]:
# Convert forecasts into dataframe

forecast_df = pd.DataFrame(
    future_forecasts,
    columns=[
        'State',
        'Week',
        'Forecasted_Sales'
    ]
)

# Display dataframe

forecast_df

       State    Week  Forecasted_Sales
0    Alabama  Week 1       207190288.0
1    Alabama  Week 2       207638992.0
2    Alabama  Week 3       208320448.0
3    Alabama  Week 4       208870368.0
4    Alabama  Week 5       209335648.0
..       ...     ...               ...
339  Wyoming  Week 4        22444164.0
340  Wyoming  Week 5        22537318.0
341  Wyoming  Week 6        22615774.0
342  Wyoming  Week 7        22680000.0
343  Wyoming  Week 8        22725202.0

[344 rows x 3 columns]

In [111]:
import tensorflow as tf
import joblib
import pickle

# Save model
model.save('lstm_sales_model.keras')

# Save scaler
joblib.dump(scaler, 'scaler.pkl')

# Save all state predictions
with open('all_state_predictions.pkl', 'wb') as f:
    pickle.dump(forecast_df, f)